### ISSUE TITLE
[BUG] Task #21933 for EnchantGUI v1.7.1 generated an exception

### ISSUE THREAD

**Issue by Andrew-Zex** [sarhatabaot/EnchantGUI#15]
i have error

```sh
java.lang.NoClassDefFoundError: me/tychsen/enchantgui/acf/BukkitCommandIssuer
        at me.tychsen.enchantgui.acf.BukkitCommandManager.getCommandIssuer(BukkitCommandManager.java:360) ~[EnchantGUI-1.7.1.jar:?]
        at me.tychsen.enchantgui.acf.BukkitCommandManager.readPlayerLocale(BukkitCommandManager.java:329) ~[EnchantGUI-1.7.1.jar:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1092) ~[?:?]
        at me.tychsen.enchantgui.acf.BukkitCommandManager.lambda$new$1(BukkitCommandManager.java:131) ~[EnchantGUI-1.7.1.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.2.jar:git-Purpur-1774]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.2.jar:git-Purpur-1774]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1520) ~[purpur-1.19.2.jar:git-Purpur-1774]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.19.2.jar:git-Purpur-1774]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1444) ~[purpur-1.19.2.jar:git-Purpur-1774]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214) ~[purpur-1.19.2.jar:git-Purpur-1774]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1774]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: me.tychsen.enchantgui.acf.BukkitCommandIssuer
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:153) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:105) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 13 more
        ```

**Comment by sarhatabaot** [comment]
I can't recreate it, can you link your full log?

**Comment by sarhatabaot** [comment]
Closed for inactivity.
