### ISSUE TITLE
InventoryClickEvent could not be handled

### ISSUE THREAD

**Issue by sarhatabaot** [sarhatabaot/EnchantGUI#4]
When clicking on an item that isn't in the shop menu,  the error shows up.
```
[20:50:35] [Server thread/ERROR]: [EnchantGUI] Inventory click event couldn't be handled.
java.lang.NullPointerException: null
        at me.tychsen.enchantgui.config.EshopConfig.getEnchantLevels(EshopConfig.java:80) ~[?:?]
        at me.tychsen.enchantgui.menu.DefaultMenuGenerator.generateEnchantMenu(DefaultMenuGenerator.java:105) ~[?:?]
        at me.tychsen.enchantgui.menu.DefaultMenuGenerator.enchantMenu(DefaultMenuGenerator.java:45) ~[?:?]
        at me.tychsen.enchantgui.menu.DefaultMenuSystem.handleMenuClick(DefaultMenuSystem.java:72) ~[?:?]
        at me.tychsen.enchantgui.event.EventManager.handleInventoryClickEvent(EventManager.java:71) ~[?:?]
        at me.tychsen.enchantgui.event.EventManager.onInventoryClickEvent(EventManager.java:49) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_191]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:520) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:505) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2162) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]
        at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]
        at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:13) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135) [spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114) [spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:895) [spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:888) [spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:123) [spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:872) [spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:805) [spigot-1.14.2.jar:git-Spigot-df0eb25-da071ec]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
```

**Comment by sarhatabaot** [comment]
Fixed in 24fe1f24739606fc7d8ccc4b2513701b33562576
