### ISSUE TITLE
[BUG] Illegal State Exception

### ISSUE THREAD

**Issue by sarhatabaot** [sarhatabaot/EnchantGUI#6]
**Describe the bug**
Error in console.

**To Reproduce**
Will update.

**Expected behavior**
No error should come up.

**Logs/Screenshots**
```log
[14:04:40] [Server thread/ERROR]: Could not pass event InventoryClickEvent to EnchantGUI v1.5.10
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[minecraft_server.jar:git-Spigot-ea7e48b-368f4e9]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[minecraft_server.jar:git-Spigot-ea7e48b-368f4e9]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[minecraft_server.jar:git-Spigot-ea7e48b-368f4e9]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[minecraft_server.jar:git-Spigot-ea7e48b-368f4e9]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2133) ~[minecraft_server.jar:git-Spigot-ea7e48b-368f4e9]
	at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[minecraft_server.jar:git-Spigot-ea7e48b-368f4e9]
	at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[minecraft_server.jar:git-Spigot-ea7e48b-368f4e9]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[minecraft_server.jar:git-Spigot-ea7e48b-368f4e9]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [minecraft_server.jar:git-Spigot-ea7e48b-368f4e9]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [minecraft_server.jar:git-Spigot-ea7e48b-368f4e9]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [minecraft_server.jar:git-Spigot-ea7e48b-368f4e9]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [minecraft_server.jar:git-Spigot-ea7e48b-368f4e9]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:909) [minecraft_server.jar:git-Spigot-ea7e48b-368f4e9]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:902) [minecraft_server.jar:git-Spigot-ea7e48b-368f4e9]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(SourceFile:103) [minecraft_server.jar:git-Spigot-ea7e48b-368f4e9]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:885) [minecraft_server.jar:git-Spigot-ea7e48b-368f4e9]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:819) [minecraft_server.jar:git-Spigot-ea7e48b-368f4e9]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.IllegalStateException: Title not set
	at com.google.common.base.Preconditions.checkState(Preconditions.java:444) ~[minecraft_server.jar:git-Spigot-ea7e48b-368f4e9]
	at net.minecraft.server.v1_14_R1.Container.getTitle(Container.java:48) ~[minecraft_server.jar:git-Spigot-ea7e48b-368f4e9]
	at org.bukkit.craftbukkit.v1_14_R1.inventory.CraftInventoryView.getTitle(CraftInventoryView.java:69) ~[minecraft_server.jar:git-Spigot-ea7e48b-368f4e9]
	at me.tychsen.enchantgui.event.EventManager.onInventoryClickEvent(EventManager.java:31) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor344.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[minecraft_server.jar:git-Spigot-ea7e48b-368f4e9]
	... 17 more
```

**Versions (Please list the version of bukkit/spigot & the plugin):**
 - Server: CraftBukkit version git-Spigot-ea7e48b-368f4e9 (MC: 1.14.4)
 - Version: EnchantGUI v1.5.10

**Additional context**

**Comment by sarhatabaot** [comment]
Outdated, this was actually fixed a while back.
